### ISSUE TITLE
Update BOLD4 to be a Taxonomy Browser search, rather than a BIN search

### ISSUE THREAD

**Issue by michaelpirrello** [dronefly-garden/dronefly#174]
Basically, change format FROM
http://www.boldsystems.org/index.php/Public_BINSearch?searchtype=records&query=Lygaeus+reclivatus
TO
http://www.boldsystems.org/index.php/Taxbrowser_Taxonpage?taxon=lygaeus+reclivatus

I think this will be simpler, give more expected results to the ordinary user, and work regardless of whether just a genus or genus+species epithet is entered.

**Comment by synrg** [comment]
Resolved by 4f701f9f1f3783939dc726b1b6e08a7222d3a385
